global using Avalonia;
global using Avalonia.Controls;
global using Avalonia.Controls.ApplicationLifetimes;
global using Avalonia.Controls.Shapes;
global using Avalonia.Input;
global using Avalonia.Interactivity;
global using Avalonia.Layout;
global using Avalonia.Markup.Xaml;
global using Avalonia.Markup.Xaml.Styling;
global using Avalonia.Media;
global using Avalonia.Threading;
global using DnsClient;
global using DnsClient.Protocol;
global using Microsoft.Extensions.Caching.Memory;
global using PingTestTool.Core;
global using PingTestTool.Service;
global using PingTestTool.Visual;
global using System.Collections.Concurrent;
global using System.Collections.ObjectModel;
global using System.ComponentModel;
global using System.Diagnostics;
global using System.IO;
global using System.Net;
global using System.Net.NetworkInformation;
global using System.Runtime.CompilerServices;
global using System.Text;

global using SysPing = System.Net.NetworkInformation.Ping;
