namespace PingTestTool.Service;

public enum Lang { En, Ru }

public static class Strings
{
    static Lang _lang = Lang.En;

    public static Lang Current => _lang;
    public static event Action? Changed;

    public static void SetLanguage(Lang lang)
    {
        _lang = lang;
        Changed?.Invoke();
    }

    public static string Get(string key) =>
        (_lang == Lang.Ru ? Ru : En).TryGetValue(key, out var v) ? v : $"[[{key}]]";

    static readonly Dictionary<string, string> En = new()
    {
        ["BtnStartText"] = "Start Test",
        ["BtnWaitText"] = "Waiting...",
        ["ErrorNoGraphData"] = "No ping data to display.",
        ["UrlEmptyError"] = "URL cannot be empty.",
        ["UrlInvalidError"] = "Invalid URL or IP address.",
        ["PingCountRangeError"] = "Packet count must be between {0} and {1}.",
        ["TimeoutMinimumError"] = "Timeout must be at least {0} ms.",
        ["InputErrorCaption"] = "Input Error",
        ["ErrorCaption"] = "Error",
        ["CriticalError"] = "Critical Error",
        ["ReplyFrom"] = "Reply from",
        ["Time"] = "Time",
        ["Ms"] = "ms",
        ["Size"] = "Size",
        ["Bytes"] = "bytes",
        ["PingError"] = "Ping error",
        ["Status"] = "Status",
        ["CriticalPingError"] = "Critical ping error",
        ["PingTest"] = "PING TEST",
        ["StartTime"] = "Start Time",
        ["EndTime"] = "End Time",
        ["Host"] = "Host",
        ["PingCount"] = "Ping Count",
        ["Timeout"] = "Timeout",
        ["DontFragment"] = "Don't Fragment",
        ["Yes"] = "Yes",
        ["No"] = "No",
        ["TestingResults"] = "TESTING RESULTS",
        ["Duration"] = "Duration",
        ["PacketStatistics"] = "Packet Statistics",
        ["PacketsSent"] = "Packets Sent",
        ["Successful"] = "Successful",
        ["Lost"] = "Lost",
        ["TimeStatistics"] = "Time Statistics",
        ["Minimum"] = "Minimum",
        ["Maximum"] = "Maximum",
        ["Average"] = "Average",
        ["Jitter"] = "Jitter",
        ["Hours"] = "hours",
        ["Minutes"] = "minutes",
        ["Seconds"] = "seconds",
        ["WindowTitle"] = "PingTestTool Utility",
        ["GraphWindowTitle"] = "Ping Graph",
        ["StartTestButton"] = "Start Test",
        ["StopButton"] = "Stop",
        ["GraphButton"] = "Graph",
        ["ExportButton"] = "Export",
        ["ClearResultsButton"] = "Clear Results",
        ["PingTabHeader"] = "Ping",
        ["TraceRouteTabHeader"] = "Trace Route",
        ["StartTraceButton"] = "Start Trace",
        ["StopTraceButton"] = "Stop Trace",
        ["SaveResultsButton"] = "Save Results",
        ["TraceAlreadyRunning"] = "Trace is already running.",
        ["WarningCaption"] = "Warning",
        ["SuccessCaption"] = "Success",
        ["TraceStarted"] = "Tracing started...",
        ["TraceError"] = "Trace error: {0}",
        ["TraceStopped"] = "Tracing stopped.",
        ["Stopping"] = "Stopping...",
        ["SpecifyUrl"] = "Please specify host address.",
        ["NoResults"] = "No results to save.",
        ["Saved"] = "Results saved successfully.",
        ["SaveError"] = "Error saving file",
    };

    static readonly Dictionary<string, string> Ru = new()
    {
        ["BtnStartText"] = "Запустить тест",
        ["BtnWaitText"] = "Ожидаем...",
        ["ErrorNoGraphData"] = "Нет данных пинга для отображения.",
        ["UrlEmptyError"] = "URL не может быть пустым.",
        ["UrlInvalidError"] = "Неверный URL или IP-адрес.",
        ["PingCountRangeError"] = "Количество пакетов должно быть между {0} и {1}.",
        ["TimeoutMinimumError"] = "Таймаут должен быть не менее {0} мс.",
        ["InputErrorCaption"] = "Ошибка ввода",
        ["ErrorCaption"] = "Ошибка",
        ["CriticalError"] = "Критическая ошибка",
        ["ReplyFrom"] = "Ответ от",
        ["Time"] = "Время",
        ["Ms"] = "мс",
        ["Size"] = "Размер",
        ["Bytes"] = "байт",
        ["PingError"] = "Ошибка пинга",
        ["Status"] = "Статус",
        ["CriticalPingError"] = "Критическая ошибка пинга",
        ["PingTest"] = "ТЕСТ PING",
        ["StartTime"] = "Время начала",
        ["EndTime"] = "Время конца",
        ["Host"] = "Хост",
        ["PingCount"] = "Кол-во пингов",
        ["Timeout"] = "Таймаут",
        ["DontFragment"] = "Не фрагментировать",
        ["Yes"] = "Да",
        ["No"] = "Нет",
        ["TestingResults"] = "ИТОГИ ТЕСТИРОВАНИЯ",
        ["Duration"] = "Длительность",
        ["PacketStatistics"] = "Статистика пакетов",
        ["PacketsSent"] = "Всего отправлено",
        ["Successful"] = "Успешно",
        ["Lost"] = "Потеряно",
        ["TimeStatistics"] = "Статистика времени",
        ["Minimum"] = "Минимальное",
        ["Maximum"] = "Максимальное",
        ["Average"] = "Среднее",
        ["Jitter"] = "Джиттер",
        ["Hours"] = "часов",
        ["Minutes"] = "минут",
        ["Seconds"] = "секунд",
        ["WindowTitle"] = "Утилита PingTestTool",
        ["GraphWindowTitle"] = "График пинга",
        ["StartTestButton"] = "Запустить тест",
        ["StopButton"] = "Стоп",
        ["GraphButton"] = "График",
        ["ExportButton"] = "Экспорт",
        ["ClearResultsButton"] = "Очистить результаты",
        ["PingTabHeader"] = "Пинг",
        ["TraceRouteTabHeader"] = "Трассировка",
        ["StartTraceButton"] = "Начать трассировку",
        ["StopTraceButton"] = "Остановить трассировку",
        ["SaveResultsButton"] = "Сохранить результаты",
        ["TraceAlreadyRunning"] = "Трассировка уже запущена.",
        ["WarningCaption"] = "Предупреждение",
        ["SuccessCaption"] = "Успех",
        ["TraceStarted"] = "Трассировка запущена...",
        ["TraceError"] = "Ошибка трассировки: {0}",
        ["TraceStopped"] = "Трассировка остановлена.",
        ["Stopping"] = "Остановка...",
        ["SpecifyUrl"] = "Укажите адрес хоста.",
        ["NoResults"] = "Нет результатов для сохранения.",
        ["Saved"] = "Результаты сохранены.",
        ["SaveError"] = "Ошибка сохранения файла",
    };
}